CREATE TABLE if not exists user_details(
	id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(150) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE if not exists room_type(
	id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	type VARCHAR(150) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE if not exists rooms(
	room_number VARCHAR(150) NOT NULL,
	room_type_id VARCHAR(150) NOT NULL,
	PRIMARY KEY (room_number),
	FOREIGN KEY (room_type_id) REFERENCES room_type(id)
);


CREATE TABLE if not exists reservation(
	id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id VARCHAR(150) NOT NULL,
	room_number VARCHAR(255) NOT NULL,
	booked_Date DATE NOT NULL,
	from_Date DATE NOT NULL,
	to_Date DATE NOT NULL,
	updated_Date DATE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES user_details(id),
	FOREIGN KEY (room_number) REFERENCES rooms(room_number)
);